// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuLuNtcVcLm_v4ERmivDU_ywdx0BoVDcc',
    appId: '1:142185378782:web:4dbd351192569b95cc234f',
    messagingSenderId: '142185378782',
    projectId: 'clot-app-4226a',
    authDomain: 'clot-app-4226a.firebaseapp.com',
    databaseURL: 'https://clot-app-4226a-default-rtdb.firebaseio.com',
    storageBucket: 'clot-app-4226a.firebasestorage.app',
    measurementId: 'G-RCFVPP6RLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3KOf5gwNq96k8s1oyK_C3I6Y1sritetw',
    appId: '1:142185378782:android:759c56abda5febd6cc234f',
    messagingSenderId: '142185378782',
    projectId: 'clot-app-4226a',
    databaseURL: 'https://clot-app-4226a-default-rtdb.firebaseio.com',
    storageBucket: 'clot-app-4226a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvttK52HDx_0u82EYRXFpqRRZ4dkjzWBE',
    appId: '1:142185378782:ios:ea6ca35dc2ab0174cc234f',
    messagingSenderId: '142185378782',
    projectId: 'clot-app-4226a',
    databaseURL: 'https://clot-app-4226a-default-rtdb.firebaseio.com',
    storageBucket: 'clot-app-4226a.firebasestorage.app',
    iosBundleId: 'com.example.clotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvttK52HDx_0u82EYRXFpqRRZ4dkjzWBE',
    appId: '1:142185378782:ios:ea6ca35dc2ab0174cc234f',
    messagingSenderId: '142185378782',
    projectId: 'clot-app-4226a',
    databaseURL: 'https://clot-app-4226a-default-rtdb.firebaseio.com',
    storageBucket: 'clot-app-4226a.firebasestorage.app',
    iosBundleId: 'com.example.clotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuLuNtcVcLm_v4ERmivDU_ywdx0BoVDcc',
    appId: '1:142185378782:web:4a1d42c9b39b432bcc234f',
    messagingSenderId: '142185378782',
    projectId: 'clot-app-4226a',
    authDomain: 'clot-app-4226a.firebaseapp.com',
    databaseURL: 'https://clot-app-4226a-default-rtdb.firebaseio.com',
    storageBucket: 'clot-app-4226a.firebasestorage.app',
    measurementId: 'G-ZDJBV1V9VR',
  );
}
